### ISSUE TITLE
Member info.

### ISSUE THREAD

**Issue by 149203** [FCC-Las-Vegas/meetings#3]
This could possibly go in the readme, but I'll add it here first.

We discussed how having a basic profile of every member available to all other members would be helpful - new folks could spend less time getting up to speed, and a central repo of this info could allow us to follow each other and encourage each other.

It could be as simple as:
#### Mike Ziethlow

Portfolio: http://mikeziethlow.com/
Codepen: http://codepen.io/149203/
Github: https://github.com/149203
Social: https://www.facebook.com/MikeFZiethlow

Members could contribute as little or much as they'd like.

**Comment by ben-denzer** [comment]
Done. https://github.com/FCC-Las-Vegas/members - Please create a pull request in the new repo.
